name: Manually Triggered benchmark for Dubbo Samples

on: [push]

permissions:
  contents: read

env:
  FORK_COUNT: 2
  FAIL_FAST: 0

jobs:
  build-source:
    name: "Build Result Convert"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: jmh_result
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8
      - name: "Build Dubbo with Maven"
        run: |
          cd ./jmh_result
          mvn clean package
  convert-trace:
    name: "Convert Trace Grpc Data"
    runs-on: ubuntu-latest
    steps:
      - name: "Run Convert"
        run: |
          rm -rf jmh_result/test-results/trace/jmh_trace_result.json
          java -jar jmh_result/target/jmh_result.jar
          
          
